---
- name: Cordon node
  command: >-
    {{ bin_dir }}/kubectl cordon
    {{ kube_override_hostname|default(inventory_hostname) }}
  delegate_to: "{{ groups['master'][0] }}"
  changed_when: false

- name: Wait for node to cordon
  command: >-
    {{ bin_dir }}/kubectl get node
    {{ kube_override_hostname|default(inventory_hostname) }}
    -o json
  register: wait_for_cordon
  retries: 100
  delay: 10
  delegate_to: "{{ groups['master'][0] }}"
  changed_when: false
  until: (wait_for_cordon['stdout'] | from_json).spec.unschedulable

- name: Drain node
  command: >-
    {{ bin_dir }}/kubectl drain
    {{ kube_override_hostname|default(inventory_hostname) }}
    --force
    --ignore-daemonsets
    --delete-emptydir-data
    --pod-selector='app!=csi-attacher,app!=csi-provisioner'
  delegate_to: "{{ groups['master'][0] }}"
  changed_when: false
